// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoInner001.proto

#ifndef PROTOBUF_INCLUDED_ProtoInner001_2eproto
#define PROTOBUF_INCLUDED_ProtoInner001_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ProtoInner001_2eproto 

namespace protobuf_ProtoInner001_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ProtoInner001_2eproto
class ProtoServerDetail;
class ProtoServerDetailDefaultTypeInternal;
extern ProtoServerDetailDefaultTypeInternal _ProtoServerDetail_default_instance_;
namespace google {
namespace protobuf {
template<> ::ProtoServerDetail* Arena::CreateMaybeMessage<::ProtoServerDetail>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class ProtoServerDetail : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoServerDetail) */ {
 public:
  ProtoServerDetail();
  virtual ~ProtoServerDetail();

  ProtoServerDetail(const ProtoServerDetail& from);

  inline ProtoServerDetail& operator=(const ProtoServerDetail& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoServerDetail(ProtoServerDetail&& from) noexcept
    : ProtoServerDetail() {
    *this = ::std::move(from);
  }

  inline ProtoServerDetail& operator=(ProtoServerDetail&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoServerDetail& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoServerDetail* internal_default_instance() {
    return reinterpret_cast<const ProtoServerDetail*>(
               &_ProtoServerDetail_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProtoServerDetail* other);
  friend void swap(ProtoServerDetail& a, ProtoServerDetail& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoServerDetail* New() const final {
    return CreateMaybeMessage<ProtoServerDetail>(NULL);
  }

  ProtoServerDetail* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoServerDetail>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoServerDetail& from);
  void MergeFrom(const ProtoServerDetail& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoServerDetail* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ProtoServerDetail)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ProtoInner001_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtoServerDetail

// string name = 1;
inline void ProtoServerDetail::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProtoServerDetail::name() const {
  // @@protoc_insertion_point(field_get:ProtoServerDetail.name)
  return name_.GetNoArena();
}
inline void ProtoServerDetail::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ProtoServerDetail.name)
}
#if LANG_CXX11
inline void ProtoServerDetail::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ProtoServerDetail.name)
}
#endif
inline void ProtoServerDetail::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ProtoServerDetail.name)
}
inline void ProtoServerDetail::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ProtoServerDetail.name)
}
inline ::std::string* ProtoServerDetail::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ProtoServerDetail.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProtoServerDetail::release_name() {
  // @@protoc_insertion_point(field_release:ProtoServerDetail.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProtoServerDetail::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ProtoServerDetail.name)
}

// int32 id = 2;
inline void ProtoServerDetail::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 ProtoServerDetail::id() const {
  // @@protoc_insertion_point(field_get:ProtoServerDetail.id)
  return id_;
}
inline void ProtoServerDetail::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:ProtoServerDetail.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ProtoInner001_2eproto
